### crate a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "test20@test.com",
    "password": "12345"
}

### sign in as an exist user (( Login ))
//eyJjb2xvciI6ImJsdWUiLCJ1c2VySWQiOjl9
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "test20@test.com",
    "password": "12345"
}
//  whitelist: true 때문에 위의 설정한 값만 들어오고 추가로 딸려온 속성은 무시함 외부의 공격을 막을 수 있음. 보안상 좋음

### get the currently signed user (( Who am i ))
GET http://localhost:3000/auth/whoami

### sign out     (( Logout ))
POST http://localhost:3000/auth/signout

### Find particular user with id
GET http://localhost:3000/auth/2

### find all user with email
GET http://localhost:3000/auth?email=abcd@efgh.com

### delete id
DELETE http://localhost:3000/auth/1215616

### update a user
PATCH http://localhost:3000/auth/2
Content-Type: application/json

{
    "email": "bbbb@aaaa.com",
    "password": "aaa"
}